<?php

namespace Urbem\CoreBundle\Repository;

/**
 * CargoRequisitoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CargoRequisitoRepository extends \Doctrine\ORM\EntityRepository
{
}
