<?php

namespace Urbem\CoreBundle\Repository;

/**
 * Class SwLogradouroRepository
 *
 * @package Urbem\CoreBundle\Repository
 */
class SwLogradouroRepository extends AbstractRepository
{
    /**
     * {@inheritdoc}
     */
    public function nextVal($campo, array $params = [])
    {
        return parent::nextVal($campo, $params); // TODO: Change the autogenerated stub
    }

    /**
     * @param $params
     * @return array
     */
    public function filtraLogradouro($params)
    {
        $where = "";
        if (isset($params['codMunicipio']) && $params['codMunicipio'] != "") {
            $where .= ($where == "")
                ? sprintf("WHERE sw_logradouro.cod_municipio = %s", $params['codMunicipio'])
                : sprintf(" AND sw_logradouro.cod_municipio = %s", $params['codMunicipio']);
        }

        if (isset($params['codUf']) && $params['codUf'] != "") {
            $where .= ($where == "")
                ? sprintf("WHERE sw_uf.cod_uf = %s", $params['codUf'])
                : sprintf(" AND sw_uf.cod_uf = %s", $params['codUf']);
        }

        if (isset($params['codTipo']) && $params['codTipo'] != "") {
            $where .= ($where == "")
                ? sprintf("WHERE sw_tipo_logradouro.cod_tipo = %s", $params['codTipo'])
                : sprintf(" AND sw_tipo_logradouro.cod_tipo = %s", $params['codTipo']);
        }

        if (isset($params['nomBairro']) && $params['nomBairro'] != "") {
            $where .= ($where == "")
                ? sprintf("WHERE UPPER( sw_bairro.nom_bairro ) like UPPER( '%s%%' )", $params['nomBairro'])
                : sprintf(" AND UPPER( sw_bairro.nom_bairro ) like UPPER( '%s%%' )", $params['nomBairro']);
        }

        if (isset($params['nomLogradouro']) && $params['nomLogradouro'] != "") {
            $where .= ($where == "")
                ? sprintf("WHERE UPPER( sw_nome_logradouro.nom_logradouro ) like UPPER( '%s%%' )", $params['nomLogradouro'])
                : sprintf(" AND UPPER( sw_nome_logradouro.nom_logradouro ) like UPPER( '%s%%' )", $params['nomLogradouro']);
        }

        if (isset($params['codLogradouroDe']) && $params['codLogradouroDe'] != "") {
            $where .= ($where == "")
                ? sprintf("WHERE sw_logradouro.cod_logradouro BETWEEN %s AND %s", $params['codLogradouroDe'], ($params['codLogradouroAte']) ? $params['codLogradouroAte'] : $params['codLogradouroDe'])
                : sprintf(" AND sw_logradouro.cod_logradouro BETWEEN %s AND %s", $params['codLogradouroDe'], ($params['codLogradouroAte']) ? $params['codLogradouroAte'] : $params['codLogradouroDe']);
        }

        if (isset($params['codBairroDe']) && $params['codBairroDe'] != "") {
            $where .= ($where == "")
                ? sprintf("WHERE sw_bairro.cod_bairro BETWEEN %s AND %s", $params['codBairroDe'], ($params['codBairroAte']) ? $params['codBairroAte'] : $params['codBairroDe'])
                : sprintf(" AND sw_bairro.cod_bairro BETWEEN %s AND %s", $params['codBairroDe'], ($params['codBairroAte']) ? $params['codBairroAte'] : $params['codBairroDe']);
        }

        if (isset($params['cepDe']) && $params['cepDe'] != "") {
            $where .= ($where == "")
                ? sprintf("WHERE imobiliario.fn_consulta_cep(sw_logradouro.cod_logradouro) BETWEEN '%s' AND '%s'", str_replace('-', '', $params['cepDe']), ($params['cepAte']) ? str_replace('-', '', $params['cepAte']) : str_replace('-', '', $params['cepDe']))
                : sprintf(" AND imobiliario.fn_consulta_cep(sw_logradouro.cod_logradouro) BETWEEN '%s' AND '%s'", str_replace('-', '', $params['cepDe']), ($params['cepAte']) ? str_replace('-', '', $params['cepAte']) : str_replace('-', '', $params['cepDe']));
        }

        $ordenacao = " ORDER BY sw_nome_logradouro.cod_logradouro ASC";
        if (isset($params['ordenacao']) && $params['ordenacao'] != "") {
            $ordenacao = sprintf(" ORDER BY sw_nome_logradouro.%s ASC", $params['ordenacao']);
        }

        $sql = sprintf("
            SELECT
                CASE WHEN sw_nome_logradouro.timestamp < (SELECT max(timestamp) FROM sw_nome_logradouro as max WHERE max.cod_logradouro = sw_nome_logradouro.cod_logradouro) 
                    THEN '3'
                    else '1'
                END as grupo
               ,sw_tipo_logradouro.cod_tipo
               ,sw_tipo_logradouro.nom_tipo||' '||sw_nome_logradouro.nom_logradouro as tipo_nome
               ,sw_tipo_logradouro.nom_tipo
               ,sw_nome_logradouro.nom_logradouro as nome_anterior
               ,sw_nome_logradouro.nom_logradouro
               ,TO_CHAR(sw_nome_logradouro.dt_inicio,'dd/mm/yyyy') as dt_inicio
               ,TO_CHAR(sw_nome_logradouro.dt_fim,'dd/mm/yyyy') as dt_fim
               ,sw_nome_logradouro.cod_norma
               ,norma.cod_tipo_norma||' - '||norma.nom_norma as descricao_norma
               ,norma.num_norma||'/'||norma.exercicio||' - '||tipo_norma.nom_tipo_norma||' - '||norma.nom_norma as descricao_norma_relatorio
               ,sw_logradouro.*
               ,initcap(sw_bairro.nom_bairro) as nom_bairro
               ,sw_municipio.nom_municipio
               ,sw_uf.nom_uf
               ,sw_uf.sigla_uf
               ,imobiliario.fn_consulta_cep(sw_logradouro.cod_logradouro) AS cep
               ,TO_CHAR(sw_nome_logradouro.timestamp,'dd/mm/yyyy hh24:mm') as data_logradouro
               ,TO_CHAR(sw_nome_logradouro.timestamp,'yyyy') as exercicio
               ,row_number() OVER (ORDER BY sw_nome_logradouro.dt_inicio) as sequencial
                  FROM sw_logradouro
            INNER JOIN sw_nome_logradouro
                    ON sw_logradouro.cod_logradouro = sw_nome_logradouro.cod_logradouro
        
            INNER JOIN sw_tipo_logradouro
                    ON sw_nome_logradouro.cod_tipo = sw_tipo_logradouro.cod_tipo
                       
            INNER JOIN sw_municipio
                    ON sw_logradouro.cod_municipio   = sw_municipio.cod_municipio
                   AND sw_logradouro.cod_uf          = sw_municipio.cod_uf
                
            INNER JOIN sw_uf
                    ON sw_municipio.cod_uf          = sw_uf.cod_uf
                
            INNER JOIN normas.norma
                    ON norma.cod_norma = sw_nome_logradouro.cod_norma
            
            INNER JOIN normas.tipo_norma
                    ON tipo_norma.cod_tipo_norma = norma.cod_tipo_norma
            
            LEFT JOIN sw_bairro_logradouro
                   ON sw_bairro_logradouro.cod_logradouro = sw_logradouro.cod_logradouro
                  AND sw_bairro_logradouro.cod_uf         = sw_logradouro.cod_uf
                  AND sw_bairro_logradouro.cod_municipio  = sw_logradouro.cod_municipio
                
            LEFT JOIN sw_bairro
                   ON sw_bairro.cod_bairro      = sw_bairro_logradouro.cod_bairro
                  AND sw_bairro.cod_uf          = sw_bairro_logradouro.cod_uf
                  AND sw_bairro.cod_municipio   = sw_bairro_logradouro.cod_municipio
            %s
            %s
        ", $where, $ordenacao);

        $query = $this->_em->getConnection()->prepare($sql);

        $query->execute();
        return $query->fetchAll();
    }
}
