<?php

namespace Urbem\CoreBundle\Repository\Concurso;

use Doctrine\ORM;
use Doctrine\ORM\Query\ResultSetMapping;
use Urbem\CoreBundle\Entity\Normas\Norma;

/**
 * EditalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditalRepository extends ORM\EntityRepository
{
    public function listarConcursoPorExercicio($exercicio)
    {
        $em = $this->getEntityManager();

        $sql = "SELECT c FROM CoreBundle:Concurso\Edital c
        INNER JOIN CoreBundle:Normas\Norma n WITH n.codNorma = c.codEdital";

        if ($exercicio != '') {
            $sql .= " AND n.exercicio = :exercicio";
        }

        $query = $em->createQuery($sql);

        if ($exercicio != '') {
            $query->setParameter('exercicio', $exercicio);
        }

        $edital = $query->getResult();

        return $edital;
    }

    /*
    select distinct(N.exercicio) from normas.norma N
    inner join concurso.edital C on C.cod_edital=N.cod_norma
    */
    public function listarExercicio()
    {
        $exercicios = $this->getEntityManager()->getRepository(Norma::class)->createQueryBuilder('n')->select('DISTINCT(n.exercicio)')
            ->join('n.fkConcursoEdital', 'e')
            ->orderBy('n.exercicio')
            ->getQuery()->getArrayResult();

        $exercicios = array_map('current', $exercicios);

        return array_combine(array_values($exercicios), array_values($exercicios));
    }
}
