# features/patrimonial/frota/veiculoTerceiro.feature
Feature: Homepage Patrimonial>Frota>Veiculo>Perfil>Terceiro
  In order to Homepage Patrimonial>Frota>Veiculo>Perfil>Terceiro
  I would be able to access the urbem

  Background:
    Given I am authenticated as "suporte" with "123"

  Scenario: Create a new Veiculo with success
    Given I am on "/patrimonial/frota/veiculo/create"
    And I fill field with uniqueId as "codMarca" with "VolksWagem" when field is "select"
    And I fill field with uniqueId as "codModelo" with "Motoniveladora 165 S" when field is "select"
    And I fill field with uniqueId as "codTipoVeiculo" with "Passeio" when field is "select"
    And I fill field with uniqueId as "codCombustivel" with "Diesel" when field is "select"
    And I fill field with uniqueId as "placa" with "mmm1234" when field is "input"
    And I fill field with uniqueId as "prefixo" with "abc" when field is "input"
    And I fill field with uniqueId as "chassi" with "9BG116GW04C400001" when field is "input"
    And I fill field with uniqueId as "kmInicial" with "5000" when field is "input"
    And I fill field with uniqueId as "numCertificado" with "73865132920" when field is "input"
    And I fill field with uniqueId as "anoFabricacao" with "2014" when field is "input"
    And I fill field with uniqueId as "anoModelo" with "2015" when field is "input"
    And I fill field with uniqueId as "categoria" with "Oficial" when field is "input"
    And I fill field with uniqueId as "capacidade" with "4" when field is "input"
    And I fill field with uniqueId as "potencia" with "1.50T" when field is "input"
    And I fill field with uniqueId as "cilindrada" with "061C" when field is "input"
    And I fill field with uniqueId as "numPassageiro" with "2" when field is "input"
    And I fill field with uniqueId as "capacidadeTanque" with "50" when field is "input"
    And I fill field with uniqueId as "cor" with "Azul" when field is "input"
    And I fill field with uniqueId as "dtAquisicao" with "01/01/2016" when field is "input"
    And I fill field with uniqueId as "codCategoria" with "AB" when field is "select"
    And I fill field with uniqueId as "verificado" with "checkField" when field is "checkbox"
    And I press "btn_create_and_list"
    Then I should see "criado com sucesso"

  Scenario: Add third vehicle with success
    Given I am on "/patrimonial/frota/veiculo/list"
    And I fill in "filter_placa_value" with "mmm1234"
    And I press "search"
    And I follow "Perfil"
    And I follow "Adicionar à Veiculo de Terceiros"
    And I fill field with uniqueId as "exercicio" with "2016" when field is "input"
    And I fill field with uniqueId as "codEntidade" with "1 - CAMARA MUNICIPAL DE VEREADORES" when field is "select"
    And I fill field with uniqueId as "numOrgao" with "2 - GABINETE DO PREFEITO" when field is "select"
    And I fill field with uniqueId as "numUnidade" with "1 - UNIDADE SUBORDINADA" when field is "select"
    And I fill field with uniqueId as "codProprietario" with "1529" when field is "inputByName"
    And I fill field with uniqueId as "codOrgao" with "S.M.A" when field is "select"
    And I fill field with uniqueId as "codSecretaria" with "S.M.F" when field is "select"
    And I fill field with uniqueId as "codUnidade" with "S.M.O.S.P" when field is "select"
    And I fill field with uniqueId as "codLocal" with "GARAGEM" when field is "select"
    And I fill field with uniqueId as "codResponsavel" with "1 - ELISSANDRO POHARSKI DESZIUTA" when field is "select"
    And I fill field with uniqueId as "dtInicio" with "24/10/2016" when field is "input"
    And I press "Salvar"
    Then I should see "Veículo de Terceiros criado com sucesso."

  Scenario: Edit third vehicle with success
    Given I am on "/patrimonial/frota/veiculo-terceiro/list"
    And I select "mmm-1234 / VolksWagem / Motoniveladora 165 S" from "filter_codVeiculo_value"
    And I press "search"
    And I follow "Editar"
    And I fill field with uniqueId as "codEntidade" with "2 - PREFEITURA MUNICIPAL DE MARIANA PIMENTEL" when field is "select"
    And I fill field with uniqueId as "numOrgao" with "3 - SECRETARIA MUNICIPAL DA ADMINISTRAÇÃO" when field is "select"
    And I fill field with uniqueId as "numUnidade" with "2 - FUNDO MUNICIPAL DE APOSENTADORIA E PENSÃO DOS SERV. PÚBLICOS" when field is "select"
    And I fill field with uniqueId as "codProprietario" with "2395" when field is "inputByName"
    And I fill field with uniqueId as "codOrgao" with "S.M.C.T" when field is "select"
    And I fill field with uniqueId as "codSecretaria" with "AGENTES CE" when field is "select"
    And I fill field with uniqueId as "codUnidade" with "MDE" when field is "select"
    And I fill field with uniqueId as "codLocal" with "COZINHA" when field is "select"
    And I fill field with uniqueId as "codResponsavel" with "2 - JOEL GHISIO" when field is "select"
    And I fill field with uniqueId as "dtInicio" with "25/10/2016" when field is "input"
    And I press "Salvar"
    Then I should see "Veículo de Terceiros atualizado com sucesso."

  Scenario: Delete third vehicle with success
    Given I am on "/patrimonial/frota/veiculo-terceiro/list"
    And I select "mmm-1234 / VolksWagem / Motoniveladora 165 S" from "filter_codVeiculo_value"
    And I press "search"
    And I follow "Excluir"
    And I press "Sim, remover"
    Then I should see "Veículo de Terceiros removido com sucesso."

  Scenario: Delete a Veiculo with success
    Given I am on "/patrimonial/frota/veiculo/list"
    And I search by "mmm1234" in "filter_placa_value" and follow to "delete"
    And I press "Sim, remover"
    Then I should see "O item foi removido com sucesso"
