# features/patrimonial/frota/veiculoLocacao.feature
Feature: Homepage Patrimonial>Frota>Veiculo>Perfil>Locacao
  In order to Homepage Patrimonial>Frota>Veiculo>Perfil>Locacao
  I would be able to access the urbem

  Background:
    Given I am authenticated as "suporte" with "123"

  Scenario: Create a new Veiculo with success
    Given I am on "/patrimonial/frota/veiculo/create"
    And I fill field with uniqueId as "codMarca" with "VolksWagem" when field is "select"
    And I fill field with uniqueId as "codModelo" with "Motoniveladora 165 S" when field is "select"
    And I fill field with uniqueId as "codTipoVeiculo" with "Passeio" when field is "select"
    And I fill field with uniqueId as "codCombustivel" with "Diesel" when field is "select"
    And I fill field with uniqueId as "placa" with "lll1234" when field is "input"
    And I fill field with uniqueId as "prefixo" with "abc" when field is "input"
    And I fill field with uniqueId as "chassi" with "9BG116GW04C400001" when field is "input"
    And I fill field with uniqueId as "kmInicial" with "5000" when field is "input"
    And I fill field with uniqueId as "numCertificado" with "73865132920" when field is "input"
    And I fill field with uniqueId as "anoFabricacao" with "2014" when field is "input"
    And I fill field with uniqueId as "anoModelo" with "2015" when field is "input"
    And I fill field with uniqueId as "categoria" with "Oficial" when field is "input"
    And I fill field with uniqueId as "capacidade" with "4" when field is "input"
    And I fill field with uniqueId as "potencia" with "1.50T" when field is "input"
    And I fill field with uniqueId as "cilindrada" with "061C" when field is "input"
    And I fill field with uniqueId as "numPassageiro" with "2" when field is "input"
    And I fill field with uniqueId as "capacidadeTanque" with "50" when field is "input"
    And I fill field with uniqueId as "cor" with "Azul" when field is "input"
    And I fill field with uniqueId as "dtAquisicao" with "01/01/2016" when field is "input"
    And I fill field with uniqueId as "codCategoria" with "AB" when field is "select"
    And I fill field with uniqueId as "verificado" with "checkField" when field is "checkbox"
    And I press "btn_create_and_list"
    Then I should see "criado com sucesso"

  Scenario: Add third vehicle with success
    Given I am on "/patrimonial/frota/veiculo/list"
    And I fill in "filter_placa_value" with "lll1234"
    And I press "search"
    And I follow "Perfil"
    And I follow "Adicionar à Veiculo de Terceiros"
    And I fill field with uniqueId as "exercicio" with "2016" when field is "input"
    And I fill field with uniqueId as "codEntidade" with "1 - CAMARA MUNICIPAL DE VEREADORES" when field is "select"
    And I fill field with uniqueId as "numOrgao" with "2 - GABINETE DO PREFEITO" when field is "select"
    And I fill field with uniqueId as "numUnidade" with "1 - UNIDADE SUBORDINADA" when field is "select"
    And I fill field with uniqueId as "codProprietario" with "1529" when field is "inputByName"
    And I fill field with uniqueId as "codOrgao" with "S.M.A" when field is "select"
    And I fill field with uniqueId as "codSecretaria" with "S.M.F" when field is "select"
    And I fill field with uniqueId as "codUnidade" with "S.M.O.S.P" when field is "select"
    And I fill field with uniqueId as "codLocal" with "GARAGEM" when field is "select"
    And I fill field with uniqueId as "codResponsavel" with "1 - ELISSANDRO POHARSKI DESZIUTA" when field is "select"
    And I fill field with uniqueId as "dtInicio" with "24/10/2016" when field is "input"
    And I press "Salvar"
    Then I should see "criado com sucesso."

  Scenario: Add Locacao with failure
    Given I am on "/patrimonial/frota/veiculo/list"
    And I fill in "filter_placa_value" with "lll1234"
    And I press "search"
    And I follow "Perfil"
    And I follow "locacao"
    And I fill field with uniqueId as "codProcesso" with "" when field is "select"
    And I fill field with uniqueId as "cgmLocatario" with "" when field is "select"
    And I fill field with uniqueId as "dtContrato" with "31/10/2016" when field is "input"
    And I fill field with uniqueId as "dtInicio" with "31/10/2016" when field is "input"
    And I fill field with uniqueId as "dtTermino" with "30/11/2016" when field is "input"
    And I press "Salvar"
    Then I should not see "criado com sucesso."

  Scenario: Add Locacao with success
    Given I am on "/patrimonial/frota/veiculo/list"
    And I fill in "filter_placa_value" with "lll1234"
    And I press "search"
    And I follow "Perfil"
    And I follow "locacao"
    And I fill field with uniqueId as "codProcesso" with "1542/2015 - Pedido de abonação de taxa de protocolo para funcionários" when field is "select"
    And I fill field with uniqueId as "cgmLocatario" with "4 - Prefeitura Municipal de Mariana Pimentel" when field is "select"
    And I fill field with uniqueId as "dtContrato" with "25/10/2016" when field is "input"
    And I fill field with uniqueId as "dtInicio" with "31/10/2016" when field is "input"
    And I fill field with uniqueId as "dtTermino" with "30/11/2016" when field is "input"
    And I fill field with uniqueId as "anoExercicio" with "2016" when field is "input"
    And I fill field with uniqueId as "codEntidade" with "3 - FMAPSP-FUNDO MUN.APOSENTADORIA E PENSAO SERV.PUBLI" when field is "select"
    And I fill field with uniqueId as "codEmpenho" with "10" when field is "input"
    And I fill field with uniqueId as "vlLocacao" with "80" when field is "input"
    And I press "Salvar"
    Then I should see "criado com sucesso."

  Scenario: Edit Locacao with failure
    Given I am on "/patrimonial/frota/veiculo/list"
    And I fill in "filter_placa_value" with "lll1234"
    And I press "search"
    And I follow "Perfil"
    And I follow "editLocacao"
    And I fill field with uniqueId as "codProcesso" with "" when field is "select"
    And I fill field with uniqueId as "cgmLocatario" with "" when field is "select"
    And I fill field with uniqueId as "dtContrato" with "28/10/2016" when field is "input"
    And I fill field with uniqueId as "dtInicio" with "31/10/2016" when field is "input"
    And I fill field with uniqueId as "dtTermino" with "30/11/2016" when field is "input"
    And I fill field with uniqueId as "anoExercicio" with "" when field is "input"
    And I press "Salvar"
    Then I should not see "atualizado com sucesso."

  Scenario: Edit Locacao with success
    Given I am on "/patrimonial/frota/veiculo/list"
    And I fill in "filter_placa_value" with "lll1234"
    And I press "search"
    And I follow "Perfil"
    And I follow "editLocacao"
    And I fill field with uniqueId as "codProcesso" with "635/2016 - Pedido de progressão de letra" when field is "select"
    And I fill field with uniqueId as "cgmLocatario" with "3849 - ABASTECEDORA INTERNA DA PREFEITURA MARIANA PIMENTEL" when field is "select"
    And I fill field with uniqueId as "dtContrato" with "26/10/2016" when field is "input"
    And I fill field with uniqueId as "dtInicio" with "28/10/2016" when field is "input"
    And I fill field with uniqueId as "dtTermino" with "31/12/2016" when field is "input"
    And I fill field with uniqueId as "anoExercicio" with "2016" when field is "input"
    And I fill field with uniqueId as "codEntidade" with "4 - PASEP" when field is "select"
    And I fill field with uniqueId as "codEmpenho" with "15" when field is "input"
    And I fill field with uniqueId as "vlLocacao" with "95" when field is "input"
    And I press "Salvar"
    Then I should see "atualizado com sucesso."

  Scenario: Delete Locacao with success
    Given I am on "/patrimonial/frota/veiculo/list"
    And I fill in "filter_placa_value" with "lll1234"
    And I press "search"
    And I follow "Perfil"
    And I follow "delete"
    And I press "Sim, remover"
    Then I should see "removido com sucesso."

  Scenario: Delete a Veiculo with success
    Given I am on "/patrimonial/frota/veiculo/list"
    And I search by "lll1234" in "filter_placa_value" and follow to "delete"
    And I press "Sim, remover"
    Then I should see "O item foi removido com sucesso"
