<?php

namespace Urbem\CoreBundle\Repository\Contabilidade;

/**
 * LancamentoEmpenhoAnuladoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LancamentoEmpenhoAnuladoRepository extends \Doctrine\ORM\EntityRepository
{
}
